routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//basic routes
Route::get('/', function () {return redirect('waitinglistnumber');});
Auth::routes();

//User routes
Route::get('waitinglistnumber', 'waitingListController@waitingListNumber')->middleware('auth');
Route::get('profile', function () {return view('profile');})->middleware('auth');
Route::get('registerOccupant', function () {return view('registerOccupant');})->name('registerOccupant');
Route::post('updateuser','updateUserController@update')->name('updateuser')->middleware('auth');
Route::post('updatePassword','updateUserController@updatePassword')->name('updatePassword')->middleware('auth');
Route::post('deleteUser','updateUserController@deleteUser')->name('deleteUser')->middleware('auth');

//Admin routes
Route::resource('waitinglist', 'waitingListController')->middleware('can:viewWaitingList');
Route::resource('occupantoverview', 'occupantOverviewController')->middleware('can:viewWaitingList');
Route::get('admin/user/{id}', 'showProfileController')->name('AdminShowUser')->middleware('can:viewWaitingList');
Route::post('admin/edituser/{id}', 'AdminEditUserController@update')->name('AdminEditUser')->middleware('can:editUser');
Route::post('admin/resetwaitinglist/{id}', 'AdminEditUserController@resetWaitingList')->name('AdminResetWaitingList')->middleware('can:editWaitingList');
Route::post('admin/deleteuser/{id}', 'AdminEditUserController@deleteUser')->name('AdminDeleteUser')->middleware('can:editUser');
Route::get('admin/roles', 'showRolesController')->name('AdminShowRoles')->middleware('can:editPermissions');
Route::resource('admin/auditlog', 'auditLogController')->middleware('can:editPermissions');

//Export Routes
Route::get('exportall', 'waitingListController@exportAll')->middleware('can:viewWaitingList');
Route::get('exportstudio', 'waitingListController@exportStudio')->middleware('can:viewWaitingList');
Route::get('exporttweekamer', 'waitingListController@exportTweeKamer')->middleware('can:viewWaitingList');
Route::get('exportdriekamer', 'waitingListController@exportDrieKamer')->middleware('can:viewWaitingList');
Route::get('exportvierkamer', 'waitingListController@exportVierKamer')->middleware('can:viewWaitingList');
Route::get('exportjongeren', 'waitingListController@exportJongeren')->middleware('can:viewWaitingList');
Route::get('exportalloccupants', 'occupantOverviewController@exportAllOccupants')->middleware('can:viewWaitingList');

resources/views/auditLog.blade.php
@extends('adminlte::page')

@section('title', 'Auditlog')

@section('content_header')
  <div style="text-align:center;">
    <h1>Audit log</h1>
  </div>

@stop

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="box">
          <div class="box-header">
            @if(Session::has('message'))
              <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
            @endif
          </div>
          <div style="text-align:center;">
            <p>Klik op het inschrijfnummer om de gegevens te bewerken</p>
          </div>
          <div class="box-body">
            <table id="waitinglist" class="table table-bordered table-hover dataTable">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Tijd (UTC)</th>
                  <th>Log</th>
                </tr>
              </thead>
            </table>
          </div>
        </div>
        <!-- /.box -->
      </div>
    </div>
  </div>

@stop

@section('css')
  <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.jqueryui.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.standalone.min.css" rel="stylesheet">

@stop
@section('js')
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
  <script src="/vendor/datatables/buttons.server-side.js"></script>

  <script type="text/javascript" language="javascript" >
  $(document).ready(function(){
    $('#waitinglist').DataTable({
      processing: true,
      serverSide: true,
      ajax: '{{ route("auditlog.index") }}',
      columns: [
        { data: 'id', name: 'id' },
        { data: 'created_at', name: 'created_at' },
        { data: 'log', name: 'log' },
      ],
    });
  });
</script>
@stop

resources/views/edituser.blade.php
@extends('adminlte::page')

@section('title', 'Mijn Account - De Molen')

@section('content_header')
    <div style="text-align:center;">
        <h1>{{$user->name }}</h1>
    </div>

@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @if(Session::has('messageSucces'))
                    <div class="alert alert-success">
                        {{ Session::get('messageSucces') }}
                    </div>
                @endif
                @if(Session::has('messageError'))
                    <div class="alert alert-danger">
                        {{ Session::get('messageError') }}
                    </div>
                @endif
                <div>
                    <label>Inschrijfnummer: {{ $user->id }}</label>
                </div>
                <div>
                    <label>Plaats op de wachtlijst: {{ $waitingListNumber }}</label>
                </div>
                <form action="{{ route('AdminEditUser', ['id' => $user->id]) }}" method="post">
                    {{ csrf_field() }}
                    <div>
                        <label>Naam: </label>
                    </div>
                    <div class="input-group mb-3">
                        <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" value="{{ $user->name }}">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user"></span>
                            </div>
                        </div>

                        @if ($errors->has('name'))
                            <div class="invalid-feedback">
                                <strong>{{ $errors->first('name') }}</strong>
                            </div>
                        @endif
                    </div>
                    <div>
                        <label>E-mail: </label>
                    </div>
                    <div class="input-group mb-3">
                        <input type="email" name="email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" value="{{ $user->email }}"
                               placeholder="voornaam@demolen.me">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                        @if ($errors->has('email'))
                            <div class="invalid-feedback">
                                <strong>{{ $errors->first('email') }}</strong>
                            </div>
                        @endif
                    </div>

                    <div>
                        <label>Geboortedatum: </label>
                    </div>
                    <div class="input-group mb-3">
                        <input type="date" name="birthday" class="form-control {{ $errors->has('birthday') ? 'is-invalid' : '' }}" value="{{ $user->birthday }}"
                               placeholder="dd/mm/yyyy">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user"></span>
                            </div>
                        </div>

                        @if ($errors->has('birthday'))
                            <div class="invalid-feedback">
                                <strong>{{ $errors->first('birthday') }}</strong>
                            </div>
                        @endif
                    </div>
                    <div>
                        <label>{{ $user->name }} wil graag per mail informatie ontvangen over: </label>
                    </div>
                    <div class="input-group">
                        <label class="form-check-label"> <input type="checkbox" name="studio" @if ($user->wantStudioMail) checked @endif>Een studio</label>
                    </div>
                    <div class="input-group">
                        <label class="form-check-label"><input type="checkbox" name="tweeKamer" @if ($user->wantTweeKamerMail) checked @endif>2-kamer appartement </label>
                    </div>
                    <div class="input-group">
                        <label class="form-check-label"><input type="checkbox" name="drieKamer" @if ($user->wantDrieKamerMail) checked @endif>3-kamer appartement </label>
                    </div>
                    <div class="input-group">
                        <label class="form-check-label"><input type="checkbox" name="vierKamer" @if ($user->wantVierKamerMail) checked @endif>4-kamer appartement </label>
                    </div>
                    <div class="input-group">
                        <label class="form-check-label"><input type="checkbox" name="jongerenWoning" @if ($user->wantJongerenWoningMail) checked @endif>Jongeren woning (maximaal 23 jaar) </label>
                    </div>
                    <div style="margin-top:10px;">
                        <label>Motivatie: </label>
                    </div>
                    <div class="input-group mb-3">
                        <textarea rows="10" name="motivation" class="form-control {{ $errors->has('motivation') ? 'is-invalid' : '' }}" placeholder="">{{ $user->motivation }}</textarea>
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-info"></span>
                            </div>
                        </div>

                        @if ($errors->has('motivation'))
                            <div class="invalid-feedback">
                                <strong>{{ $errors->first('motivation') }}</strong>
                            </div>
                        @endif
                    </div>
                    <div style="margin-top:10px;">
                        @if ($user->occupant)
                            <label> {{$user->name}} is op dit moment ingeschrijven als bewoner. Vink onderstaand vinkje uit om geen bewoner meer te laten zijn.</label>
                        @else
                            <label> {{$user->name}} is op dit moment NIET ingeschrijven als bewoner. Vink onderstaand vinkje aan om hem/haar bewoner te maken.</label>
                        @endif
                    </div>

                    <div class="input-group">
                        <label class="form-check-label"> <input type="checkbox" name="occupant" @if ($user->occupant) checked @endif> is bewoner vinkje</label>
                    </div>
                    <div style="margin-top:10px;">
                        <label>Huisnummer indien bewoner: </label>
                    </div>
                    <div class="input-group mb-3">
                        <input type="text" name="houseNumber" class="form-control {{ $errors->has('houseNumber') ? 'is-invalid' : '' }}" value="{{ $user->houseNumber }}">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-info"></span>
                            </div>
                        </div>

                        @if ($errors->has('houseNumber'))
                            <div class="invalid-feedback">
                                <strong>{{ $errors->first('houseNumber') }}</strong>
                            </div>
                        @endif
                    </div>

                    @can('editPermissions')
                        <div style="margin-top:10px;">
                            <label>Rollen: </label>
                        </div>
                        <div class="input-group">
                            <label class="form-check-label"> <input type="checkbox" name="waitingListViewer" @if ($user->hasRole('waitingListViewer')) checked @endif>Wachtlijst bekijken</label>
                        </div>
                        <div class="input-group">
                            <label class="form-check-label"><input type="checkbox" name="waitingListAdmin" @if ($user->hasRole('waitingListAdmin')) checked @endif>Wachtlijst-editor</label>
                        </div>
                        <div class="input-group">
                            <label class="form-check-label"><input type="checkbox" name="superAdmin" @if ($user->hasRole('superAdmin')) checked @endif>Super Admin</label>
                        </div>
                    @endcan
                    @can('editUser')
                        <button type="submit" class="btn btn-primary btn-block btn-flat">
                            Bijwerken
                        </button>
                    @endcan
                    @can('editWaitingList')
                </form>
                <form class="reset" action="{{ route('AdminResetWaitingList', ['id' => $user->id]) }}" method="post">
                    <div>
                        {{ csrf_field() }}
                        <div>
                            <label>Plaats onderaan de wachtlijst </label>
                        </div>
                        <p>
                            Door op onderstaande knop te klikken wordt {{$user->name}} onderaan de wachtwoord geplaatst.
                        </p>
                        <button type="submit" class="btn btn-primary btn-danger btn-block btn-flat">
                            Plaats onderaan de wachtlijst
                        </button>
                    </div>
                </form>
                @endcan
                @can('editUser')
                    <form class="delete" action="{{ route('AdminDeleteUser',['id' => $user->id]) }}" method="post">
                        <div>
                            {{ csrf_field() }}
                            <div>
                                <label>Uitschrijven </label>
                            </div>
                            <p>
                                Door op onderstaande knop te klikken worden al gegevens van {{$user->name}} verwijderd.
                            </p>
                            <button type="submit" class="btn btn-primary btn-danger btn-block btn-flat">
                                Verwijder alle gegevens
                            </button>
                        </div>
                    </form>
                @endcan
            </div>
        </div>
    </div>
@stop

@section('css')

@stop

@section('js')
    @stack('js')
    @yield('js')

    <script>
        $(".delete").on("submit", function(){
            return confirm("Weet je het heel zeker? Deze knop werkt echt, alle gegevens van {{ $user->name }} zullen worden verwijderd.");
        });
    </script>
    <script>
        $(".reset").on("submit", function(){
            return confirm("Weet je het heel zeker? Deze knop werkt echt. {{ $user->name }} zal onderaan de wachtlijst geplaatst worden.");
        });
    </script>


@endsection

resources/views/emailSussesRegistration.blade.php
@component('mail::message')
{{-- Greeting --}}
Hi,<br>
<br>

Bedankt voor je inschrijving! Vanaf nu zit je in onze database en zullen we je op de hoogte houden van vrijgekomen woningen van jouw voorkeur. Jouw inschrijfnummer is te vinden in jouw persoonlijk profiel op de website. <br>
<br>
Wil je je alvast inlezen in onze selectieprocedure? Dit kan via deze link: <a href="https://www.demolen.me/wonen-in-de-molen/">https://www.demolen.me/wonen-in-de-molen/</a>  <br>
<br>
Met vriendelijke groet, <br>
De selectiecommissie van wooncomplex de Molen

@endcomponent

resources/views/occupantOverview.blade.php
@extends('adminlte::page')

@section('title', 'Bewonersoverzicht')

@section('content_header')
    <div style="text-align:center;">
        <h1>Bewonersoverzicht de Molen</h1>
    </div>
@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        @if(Session::has('message'))
                            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
                        @endif
                    </div>
                    <div style="text-align:center;">
                        <p>Klik op het inschrijfnummer om de gegevens te bewerken</p>
                    </div>
                    <div class="box-body">
                        <table id="occupantoverview" class="table table-bordered table-hover dataTable">
                            <thead>
                            <tr>
                                <th>Inschrijfnummer</th>
                                <th>Huisnummer</th>
                                <th>Naam</th>
                                <th>Email</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- /.box -->
            </div>
            <div class="col-md-3" style="margin-bottom: 10px; margin-top: 10px;">
                <a class="btn btn-primary btn-block btn-flat" href="{{action('occupantOverviewController@exportAllOccupants')}}">Export alle bewoners</a>
            </div>
        </div>
    </div>
@stop

@section('css')
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.jqueryui.min.css" rel="stylesheet">

@stop
@section('js')
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="/vendor/datatables/buttons.server-side.js"></script>

    <script type="text/javascript" language="javascript" >
        $(document).ready(function(){
            $('#occupantoverview').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route("occupantoverview.index") }}',
                "order": [[1, 'asc']],
                columns: [
                    { data: 'id', name: 'id', render: function(data, type, full, meta) {return '<a href="admin/user/'+data+'">'+ data + '</a>'}},
                    { data: 'houseNumber', name:'houseNumber'},
                    { data: 'name', name: 'name' },
                    { data: 'email', name: 'email' },
                ],
            });
        });
    </script>
@stop

resources/views/roles.blade.php
@extends('adminlte::page')

@section('title', 'Rollenoverzicht')

@section('content_header')

  <div style="text-align:center;">
    <h1>Rollenoverzicht</h1>
  </div>

@stop

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="box">
          <div class="box-body">
            <div style="text-align:center;">
              <h3> Super Admins </h3>
              @foreach ($usersSuperAdmins as $superAdmin)
                {{ $superAdmin->name }} - {{ $superAdmin->email}} <a href="{{config('app.url')}}/admin/user/{{$superAdmin->id}}">edit</a><br>
              @endforeach
              <br>
              <h3> Wachtlijst-editor</h3>
              @foreach ($usersWaitingListAdmins as $waitingListAdmin)
                {{ $waitingListAdmin->name }} - {{ $waitingListAdmin->email}} <a href="{{config('app.url')}}/admin/user/{{$waitingListAdmin->id}}">edit</a><br>
              @endforeach
              <br>
              <h3> Wachtlijst bekijken</h3>
              @foreach ($usersWaitingListViewers as $waitingListViewer)
                {{ $waitingListViewer->name }} - {{ $waitingListViewer->email}} <a href="{{config('app.url')}}/admin/user/{{$waitingListViewer->id}}">edit</a><br>
              @endforeach

            </div>
          </div>
          <!-- /.box -->
        </div>
      </div>
    </div>
  </div>
@stop

@section('css')

@stop

resources/views/rooms.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>@lang('rooms.title')</h1>
@stop

@section('content')
    <p>Welcome to this beautiful admin panel.</p>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

resources/views/waitingList.blade.php
@extends('adminlte::page')

@section('title', 'Wachtlijst de Molen')

@section('content_header')
  <div style="text-align:center;">
    <h1>Wachtlijst de Molen</h1>
  </div>

@stop

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="box">
          <div class="box-header">
            @if(Session::has('message'))
              <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
            @endif
          </div>
          <div style="text-align:center;">
            <p>Klik op het inschrijfnummer om de gegevens te bewerken</p>
          </div>
          <div class="box-body">
            <table id="waitinglist" class="table table-bordered table-hover dataTable">
              <thead>
                <tr>
                  <th>Inschrijfnummer</th>
                  <th>Wachtlijstnummer</th>
                  <th>Naam</th>
                  <th>Email</th>
                  <th>Wachtlijst datum (UTC)</th>
                </tr>
              </thead>
            </table>
          </div>
        </div>
        <!-- /.box -->
      </div>
      <div class="col-md-3" style="margin-bottom: 10px; margin-top: 10px;">
        <a class="btn btn-primary btn-block btn-flat" href="{{action('waitingListController@exportAll')}}">Export de hele wachtlijst </a>
      </div>
      <div class="col-md-12"style="text-align:center;">
        <h3>Exports voor Mailchimp (inclusief bewoners)</h3>
      </div>
      <div class="col-md-3" style="margin-bottom: 10px; margin-top: 10px;">
        <a class="btn btn-primary btn-block btn-flat" href="{{action('waitingListController@exportStudio')}}">Export Studio</a>
      </div>
      <div class="col-md-3" style="margin-bottom: 10px; margin-top: 10px;">
        <a class="btn btn-primary btn-block btn-flat" href="{{action('waitingListController@exportTweeKamer')}}">Export 2 kamer</a>
      </div>
      <div class="col-md-3" style="margin-bottom: 10px; margin-top: 10px;">
        <a class="btn btn-primary btn-block btn-flat" href="{{action('waitingListController@exportDrieKamer')}}">Export 3 kamer</a>
      </div>
      <div class="col-md-3" style="margin-bottom: 10px; margin-top: 10px;">
        <a class="btn btn-primary btn-block btn-flat" href="{{action('waitingListController@exportVierKamer')}}">Export 4 kamer</a>
      </div>
      <div class="col-md-3" style="margin-bottom: 10px; margin-top: 10px;">
        <a class="btn btn-primary btn-block btn-flat" href="{{action('waitingListController@exportJongeren')}}">Export jongeren</a>
      </div>
    </div>
  </div>

@stop

@section('css')
  <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.jqueryui.min.css" rel="stylesheet">

@stop
@section('js')
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
  <script src="/vendor/datatables/buttons.server-side.js"></script>

  <script type="text/javascript" language="javascript" >
  $(document).ready(function(){
    $('#waitinglist').DataTable({
      processing: true,
      serverSide: true,
      ajax: '{{ route("waitinglist.index") }}',
      "order": [[4, 'asc']],
      columns: [
        { data: 'id', name: 'id', render: function(data, type, full, meta) {return '<a href="admin/user/'+data+'">'+ data + '</a>'}},
        { data: 'waitingListNumber', name:'waitingListNumber'},
        { data: 'name', name: 'name' },
        { data: 'email', name: 'email' },
        { data: 'waitingListDate', name: 'waitingListDate' },

      ],
    });
  });
</script>
@stop

resources/views/waitingListNumber.blade.php
@extends('adminlte::page')

@section('title', 'Wachtlijst nummer')

@section('content_header')
    <div style="text-align:center;">
        <h1>Wachtlijstnummer</h1>
    </div>

@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-body">
                        <div style="text-align:center;">
                            <h2> Je staat op dit moment op plek <b>{{ $waitingListNumber ?? 'onbekend' }}</b> van de wachtlijst. </h2>
                            <br>
                            <h2>Je inschrijfnummer is <b>{{ Auth::user()->id }}</b>. Dit is een uniek nummer van jouw inschrijving en zal niet veranderen.<br>
                                Geef altijd het inschrijfnummer door als je reageert op een woning. </h2><br>
                            <h2>Wil je iets veranderen aan je inschrijving, klik dan in het menu op profiel.</h2><br>
                            <h2>Ben een bewoner of ondersteun je een zorgvragende bewoner en zie je dit scherm. Je inschrijving is in dat geval nog niet volledig verwerkt. Stuur daarom een mail naar <a href="mailto:bestuur@demolen.me">bestuur@demolen.me</a>.
                                Het bestuur zal je inschrijving vervolgens verwerken. </h2>
                        </div>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')

@stop

resources/views/waitingListNumberOccupant.blade.php
@extends('adminlte::page')

@section('title', 'Wachtlijst nummer')

@section('content_header')
  <div style="text-align:center;">
    <h1></h1>
  </div>

@stop

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="box">
          <div class="box-body">
            <div style="text-align:center;">
              <h2> Je staat op dit moment op ingeschreven als bewoner. Je hoeft verder niks te doen. </h2>
              <br>
              <h2> Je inschrijfnummer is <b>{{ Auth::user()->id }}</b>.<br>
                Geef altijd het inschrijfnummer door als je reageert op een woning. </h2> <br>
                <h2> Wil je iets veranderen aan je inschrijving, klik dan in het menu op profiel.</h2>
            </div>
          </div>
          <!-- /.box -->
        </div>
      </div>
    </div>
  </div>
@stop

@section('css')

@stop